<a href="https://colab.research.google.com/github/Jesuscua/Automatizacion_infra/blob/main/11_06_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Array de una dimensión
import numpy as np
al = np.array([1,2,3])
print(al)

[1 2 3]


In [3]:
#Array de dos dimensiones
a2=np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [5]:
#Array de tres dimensiones
a3=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
print (np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [9]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [11]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0])#Acceso al elemento de la fila 1 columna 0

4


In [13]:
print(a[1][0])

4


In [14]:
print(a[:, 0:2])

[[1 2]
 [4 5]]


In [17]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a% 2 == 0)])

[2 4 6]
