<a href="https://colab.research.google.com/github/Jesuscua/Automatizacion_infra/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Acceso a los elementos de un array

In [3]:
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6]])
#Acceso al elemento de la fila 1 columna 0
print(a[1, 0])

4


In [4]:
#Otra forma de acceder al mismo elemento
print(a[1][0])

4


In [5]:
print(a[:, 0:2])

[[1 2]
 [4 5]]


##Filtrado de elementos de un array

In [14]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a% 3 <= 1)])

[1 3 4 6]


In [23]:
print(a[(a% 5 == 2) &  (a> 1)])

[2]


##Operaciones matemáticas con arrays

In [9]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([[1, 1, 1], [2, 2, 2]])
print(a+b)

[[2 3 4]
 [6 7 8]]


In [10]:
print(a/b)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [11]:
print(a** 2)

[[ 1  4  9]
 [16 25 36]]


##Operaciones matemáticas a nivel de array

In [25]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([[1, 1], [2, 2], [3, 3]])
print(a.dot(b))

[[14 14]
 [32 32]]


In [26]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]
